### ISSUE TITLE
feature request : backspace on empty square → make the cursor go one square before

### ISSUE THREAD

**Issue by emmahicks** [Leo-Nicolle/mots-fleches#44]
could it be possible that hitting backspace when on an empty square makes the cursor go to the previous square (ie one square up when on vertical edit, one square left when on horizontal edit), in order to use the mouse less ?  =P

**Comment by Leo-Nicolle** [comment]
Yes Actually I fixed it on develop :) . I'll release end of the week, you'll see there are lots of new things !!
