### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by latsami** [Leo-Nicolle/mots-fleches#57]
Hello,
merci pour ton super outil :)
J'ai enfin pris le temps de faire une grille complète.
J'ai voulu changer les styles,, mais certaines choses sont à améliorer:
- la typo n'est pas appliquée (en fait oui et non, le CSS ets bien là, mais je pense que la typo n'est pas chargée en @font-face)
- la taille des fontes sont difficiles à gérer, j'ai dû mettre taille 1pt pour les définitions pour que ça rentre. Et par défaut, la taille de corps des définitions est énorme et donc je ne comprenais pas qu'on pouvait écrire dans les cases.
- pouvoir régler l'interlignage dans les définitions
- autoriser les césures dans les définitions
- pouvoir renommer les grilles
- parfois quand on choisit un mot (mode marteau), plein de cases deviennent noires. J'imagine que c'est parce que ça bloque les possibilités autour? Un Ctrl+Z pourrait être le bienvenu à ce moment-là, mais c'est du chipotage.
 

Testé sur Chromium Version 118.0.5993.117 (Build officiel) Arch Linux (64 bits). 

Déjà un grand merci! :D

**Comment by Leo-Nicolle** [comment]
Salut ! Content d'avoir des retours :)

  - *La typo n'est pas appliquée*: As tu sélectionnes une typo dans la liste ou upload une typo a toi ? Tu as une erreur dans la console ? 
  -  *taille des typos*: normalement la taille de la typo dans les cases de définitions est égale a *tailledescellues/4*, mais il y a le champ `taille` qui permet de réduire (la taille finale est *taille \* tailledescellules/4*). J'ai fait ca pour faciliter la vie des utilisateurs, qui n'ont pas a calculer la bonne taille de typo, mais c'etait peut etre une erreur, qu'en penses tu ? Qu'est-ce que tu ne comprenais pas ? Je n'ai pas compris :).
 - *Interlignage*: Ce n'est pas la première fois qu'on me le demande :). Tu voudrais pouvoir le changer case par case ? Ou juste le définir globalement et l'appliquer sur toutes les cases ? 
 -  *Cesures*: Tu veux dire un retour a la ligne automatique ? Avec l'option ou on coupe les mots avec un tiret ? Oui ce serait pratique, ce n'est pas implémenté pour l'instant parce que la grille est affichée en SVG, et le SVG ne gère pas les césures de la meme manière que `textarea` (qui remplace la case lors de l'édition de celle-ci), donc t'as pas de WYSIWYG, mais bon, j'ai une idée, on verra si ca marche.
 - *renommer*: C'est deja la, mais c'est caché, il faut clique sur l'engrenage dans l'éditeur de grille, tu peux changer la taille, le titre et mettre un com.
 - *Cases noires*: Exactement. En fait c'est pas facile de savoir si un mot va foutre le bordel ou pas ( en tout cas de manière rapide avec tous les mots du dico), donc j'ai un truc qui calcule une probabilité de foutre le bordel, mais c'est pas exacte, c'est pourquoi un mot qui apparaît dans le haut de la liste parfois bloque tout. Peut être que j'y arriverai, je ne sais pas. En attendant **Ctrl-Z** c'est une bonne idee, et pas si difficile a mettre en place.
